# Expose ports for local development
services:
  api:
    image: qwl-api-dev
    build:
      target: build
    command: ["watchexec", "--poll", "500ms", "--restart", "-e", "gleam", "--", "gleam", "run"]
    volumes:
      - ./backend:/app
    working_dir: /app
  db:
    # for "make squrrel"
    ports:
      - "${DB_PORT}:5432"

  frontend:
    image: qwl-frontend-dev
    build:
      target: builder
    command: ["gleam", "run", "-m", "lustre/dev", "start", "--host=0.0.0.0", "--port=${FRONTEND_DEV_PORT}"]
    ports:
      - "${FRONTEND_DEV_PORT}:${FRONTEND_DEV_PORT}"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

