# Overrides for local development
services:
  api:
    image: qwl-api-dev
    build:
      target: build
    command: ["watchexec", "--poll", "500ms", "--restart", "-e", "gleam", "--", "gleam", "run"]
    volumes:
      - .:/app
    working_dir: /app/backend
    environment:
      - CLICOLOR_FORCE=1
      - FORCE_COLOR=1
    depends_on:
      db:
        condition: service_healthy
      db-migrate:
        condition: service_completed_successfully

  db-migrate:
    image: amacneil/dbmate:2.24.0
    volumes:
      - ./db:/db
    networks:
      - backend-net
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable"
    command: up
    depends_on:
      db:
        condition: service_healthy

  db:
    # for "make squrrel"
    ports:
      - "${DB_PORT}:5432"

  frontend:
    image: qwl-frontend-dev
    build:
      target: builder
    command: ["gleam", "run", "-m", "lustre/dev", "start", "--host=0.0.0.0", "--port=${FRONTEND_DEV_PORT}"]
    ports:
      - "${FRONTEND_DEV_PORT}:${FRONTEND_DEV_PORT}"
    volumes:
      - .:/app
    working_dir: /app/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
