//// Code generated by parrot. DO NOT EDIT.
////

import gleam/dynamic/decode
import parrot/dev

pub type AddTag {
  AddTag(id: Int, name: String)
}

pub fn add_tag(name name: String) {
  let sql = "insert into tag (name) values ($1) returning id, name"
  #(sql, [dev.ParamString(name)], add_tag_decoder())
}

pub fn add_tag_decoder() -> decode.Decoder(AddTag) {
  use id <- decode.field(0, decode.int)
  use name <- decode.field(1, decode.string)
  decode.success(AddTag(id:, name:))
}

pub type GetAllTags {
  GetAllTags(id: Int, name: String)
}

pub fn get_all_tags() {
  let sql = "select id, name from tag"
  #(sql, [], get_all_tags_decoder())
}

pub fn get_all_tags_decoder() -> decode.Decoder(GetAllTags) {
  use id <- decode.field(0, decode.int)
  use name <- decode.field(1, decode.string)
  decode.success(GetAllTags(id:, name:))
}
